// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCYnDQX1MXIYxT09_SDTrK2eZMPOQNig',
    appId: '1:1091330807762:android:dca02ab558c6776e8b5a0b',
    messagingSenderId: '1091330807762',
    projectId: 'fir-bloc-b4e53',
    storageBucket: 'fir-bloc-b4e53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmMbRprnN9HH_PS0NYUaKhZN8cz5-F31Y',
    appId: '1:1091330807762:ios:75fe75e2d6d569ef8b5a0b',
    messagingSenderId: '1091330807762',
    projectId: 'fir-bloc-b4e53',
    storageBucket: 'fir-bloc-b4e53.firebasestorage.app',
    iosBundleId: 'com.prasannataBaniya.flutterBlocFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeZ0MMis0gD3fixWHD1U9fR32hmYjefXA',
    appId: '1:1091330807762:web:6ba705d8123c56718b5a0b',
    messagingSenderId: '1091330807762',
    projectId: 'fir-bloc-b4e53',
    authDomain: 'fir-bloc-b4e53.firebaseapp.com',
    storageBucket: 'fir-bloc-b4e53.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeZ0MMis0gD3fixWHD1U9fR32hmYjefXA',
    appId: '1:1091330807762:web:6ba705d8123c56718b5a0b',
    messagingSenderId: '1091330807762',
    projectId: 'fir-bloc-b4e53',
    authDomain: 'fir-bloc-b4e53.firebaseapp.com',
    storageBucket: 'fir-bloc-b4e53.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmMbRprnN9HH_PS0NYUaKhZN8cz5-F31Y',
    appId: '1:1091330807762:ios:75fe75e2d6d569ef8b5a0b',
    messagingSenderId: '1091330807762',
    projectId: 'fir-bloc-b4e53',
    storageBucket: 'fir-bloc-b4e53.firebasestorage.app',
    iosBundleId: 'com.prasannataBaniya.flutterBlocFirebase',
  );

}